### ISSUE TITLE
Side Bar too big

### ISSUE THREAD

**Issue by annafralberts** [openbudgets/openbudgets.github.io#22]
My colleague just pointed out that the sidebar is quite large in comparison to the main text. 
Can you adjust that?

**Comment by smth** [comment]
Is it the width of the content, or the amount of padding that you do not like? I ask because looking at the content, I think it would become difficult to read if any narrower. This is how it currently looks:

![sidebar](https://cloud.githubusercontent.com/assets/1375708/17658791/00d43026-62c6-11e6-9133-3a9389642998.jpg)

There is quite a lot of padding between the two columns (on large screens), as suggested in the [wireframe](https://github.com/openbudgets/openbudgets.github.io/issues/10#issuecomment-230751415).

**Comment by annafralberts** [comment]
It is the amount of padding. Now I see that Bela and Cecile made it like that too, but if you could adjust it so there is less white space (especially on the right), that would look better I think.

**Comment by smth** [comment]
OK. Is that better? http://okfnlabs.org/openbudgetseu-staging/

**Comment by annafralberts** [comment]
More like this :)

![screenshot 2016-08-18 14 07 42](https://cloud.githubusercontent.com/assets/12712917/17773197/7550829a-654d-11e6-9f3f-c67f22b57746.png)

**Comment by smth** [comment]
OK, updated http://okfnlabs.org/openbudgetseu-staging/
