### ISSUE TITLE
Introduce second footer, rearrange sections

### ISSUE THREAD

**Issue by seegerseeger** [openbudgets/openbudgets.github.io#9]
Section changes:
In current header: 
About -> Move to new footer
Resources -> remove entirely 
Place 'Sign up for the Newsletter' button on the right of the sections in the header

In new footer:
create 'Work Packages' section
create 'Deliverables' section
create 'Partners' section
create 'Press' section

**Comment by cecilaki** [comment]
About new sections, do we keep the same content as in the existing:
- [Work Packages](http://openbudgets.eu/about/work-packages/) section
- [Deliverables](http://openbudgets.eu/about/deliverables/)  
- [Partners](http://openbudgets.eu/about/partners/)
- [Press](http://openbudgets.eu/press/) 

To make sure, the [resources section and content ](http://openbudgets.eu/resources/)will disappear from the website, correct? Assuming those resources will be placed later in the OpenSpending.org umbrella. (poke @annafralberts ) 

Signup for the Newsletter > I suggest we move this to the sidebar rather than having it in the header.

**Comment by seegerseeger** [comment]
For the section/content re-arrangement, consult the mockup and comments in Issue #10.
